name: Build MyIaC

on:
  push:
    branches: [issue/*, feature/*, update/*, fix/*, master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Test Coverage
        run: go test ./...  -coverprofile=coverage.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: go build -v cmd/myiac/myiac.go

      - name: Test cli
        run: ./myiac --help | grep "Infrastructure as code"