name: Build MyIaC

on:
  push:
    branches: [issue/*, feature/*, update/*, fix/*, master]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v cmd/myiac/myiac.go

      - name: Test
        run: ./myiac --help | grep "Infrastructure as code"
